/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import services.DBManager;
import services.JsonManager;
import services.OkHTTPManager;
import model.ResultOfCountry;

public class JFrameMain extends javax.swing.JFrame {

    List<ResultOfCountry> countriesResults; // Για να κρατάω τα αποτελέσματα του HTTP query
    DBManager db;
    long[] stats;

    /**
     * Creates new form NewJFrame
     */
    public JFrameMain() {
        initComponents();

        db = new DBManager(); // κάνω σύνδεση με το persistence unit
        if (db.getEm()==null){
            JOptionPane.showMessageDialog(null, "Σφάλμα σύνδεσης με τον DB Server. Δοκιμάστε να τον ξεκινήσετε!", "Σύνδεση με ΒΔ", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        countriesResults = new ArrayList<>();

        stats = db.dbRecordsInfo();
        jLabelCountriesInDB.setText(String.valueOf(stats[0]));
        jLabelDeathsInDB.setText(String.valueOf(stats[1]));
        jLabelRecoveredInDB.setText(String.valueOf(stats[2]));
        jLabelConfirmedInDB.setText(String.valueOf(stats[3]));
        jLabelTotalRecords.setText(String.valueOf(stats[4]));
    }

    public List<ResultOfCountry> getCountriesResults() {
        return countriesResults;
    }

    public void setCountriesResults(List<ResultOfCountry> countriesResults) {
        this.countriesResults = countriesResults;
    }

    public void setStats(long[] stats) {
        this.stats = stats;
    }

    public long[] getStats() {
        return stats;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogManageData = new javax.swing.JDialog();
        jLabelStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonConfirmed = new javax.swing.JRadioButton();
        jRadioButtonRecovered = new javax.swing.JRadioButton();
        jRadioButtonDeaths = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonInsertCountries = new javax.swing.JButton();
        jButtonInsertData = new javax.swing.JButton();
        jButtonDeleteCountries = new javax.swing.JButton();
        jButtonDeleteData = new javax.swing.JButton();
        jButtonLoadFromHttpAPI = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCountriesInDB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelDeathsInDB = new javax.swing.JLabel();
        jLabelRecoveredInDB = new javax.swing.JLabel();
        jLabelConfirmedInDB = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTotalRecords = new javax.swing.JLabel();
        buttonGroupDataType = new javax.swing.ButtonGroup();
        jMenuBarBasic = new javax.swing.JMenuBar();
        jMenuFunctions = new javax.swing.JMenu();
        jMenuFunctionsManageData = new javax.swing.JMenuItem();
        jMenuFunctionsViewDataTabular = new javax.swing.JMenuItem();
        jMenuFunctionsViewDataOnMap = new javax.swing.JMenuItem();
        jSeparatorFunctions = new javax.swing.JPopupMenu.Separator();
        jMenuFunctionsExit = new javax.swing.JMenuItem();

        jDialogManageData.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogManageData.setTitle("Διαχείριση δεδομένων");
        jDialogManageData.setBounds(new java.awt.Rectangle(300, 300, 810, 180));
        jDialogManageData.setLocation(new java.awt.Point(300, 300));
        jDialogManageData.setModal(true);
        jDialogManageData.setResizable(false);
        jDialogManageData.setSize(new java.awt.Dimension(810, 200));
        jDialogManageData.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogManageDataWindowClosing(evt);
            }
        });

        jLabelStatus.setText("Κατάσταση - ");
        jLabelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Τύπος δεδομένων", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        buttonGroupDataType.add(jRadioButtonConfirmed);
        jRadioButtonConfirmed.setText("Κρούσματα");
        jRadioButtonConfirmed.setActionCommand("confirmed");

        buttonGroupDataType.add(jRadioButtonRecovered);
        jRadioButtonRecovered.setText("Ανάρρωσαν");
        jRadioButtonRecovered.setActionCommand("recovered");

        buttonGroupDataType.add(jRadioButtonDeaths);
        jRadioButtonDeaths.setSelected(true);
        jRadioButtonDeaths.setText("Θάνατοι");
        jRadioButtonDeaths.setActionCommand("deaths");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDeaths)
                    .addComponent(jRadioButtonRecovered)
                    .addComponent(jRadioButtonConfirmed))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButtonDeaths)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonRecovered)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonConfirmed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ενέργειες", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jButtonInsertCountries.setText("Εισαγωγή χωρών");
        jButtonInsertCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertCountriesActionPerformed(evt);
            }
        });

        jButtonInsertData.setText("Εισαγωγή δεδομένων");
        jButtonInsertData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertDataActionPerformed(evt);
            }
        });

        jButtonDeleteCountries.setText("Διαγραφή χωρών");
        jButtonDeleteCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCountriesActionPerformed(evt);
            }
        });

        jButtonDeleteData.setText("Διαγραφή δεδομένων");
        jButtonDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonInsertCountries))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonInsertData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonDeleteCountries)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonDeleteData)
                        .addGap(23, 23, 23))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertCountries)
                    .addComponent(jButtonDeleteCountries))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteData)
                    .addComponent(jButtonInsertData))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jButtonLoadFromHttpAPI.setText("Φόρτωση");
        jButtonLoadFromHttpAPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadFromHttpAPIActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Κατάσταση ΒΔ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Χώρες:");

        jLabelCountriesInDB.setText("CountriesInDB");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Θάνατοι:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ανάρρωσαν:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Κρούσματα:");

        jLabelDeathsInDB.setText("DeathsInDB");

        jLabelRecoveredInDB.setText("RecoveredInDB");

        jLabelConfirmedInDB.setText("ConfirmedInDB");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Σύνολο:");

        jLabelTotalRecords.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTotalRecords.setText("TotalRecords");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelConfirmedInDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTotalRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDeathsInDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRecoveredInDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCountriesInDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelCountriesInDB))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelDeathsInDB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRecoveredInDB)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelConfirmedInDB)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalRecords)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogManageDataLayout = new javax.swing.GroupLayout(jDialogManageData.getContentPane());
        jDialogManageData.getContentPane().setLayout(jDialogManageDataLayout);
        jDialogManageDataLayout.setHorizontalGroup(
            jDialogManageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogManageDataLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDialogManageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogManageDataLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonLoadFromHttpAPI)))
                .addGap(18, 18, 18)
                .addGroup(jDialogManageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jDialogManageDataLayout.setVerticalGroup(
            jDialogManageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogManageDataLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDialogManageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(jDialogManageDataLayout.createSequentialGroup()
                        .addGroup(jDialogManageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogManageDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLoadFromHttpAPI))))
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Σύστημα στατιστικών COVID19");
        setLocation(new java.awt.Point(250, 250));
        setName("basicFrame"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuFunctions.setText("Λειτουργίες");

        jMenuFunctionsManageData.setText("Διαχείριση δεδομένων Covid19");
        jMenuFunctionsManageData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFunctionsManageDataActionPerformed(evt);
            }
        });
        jMenuFunctions.add(jMenuFunctionsManageData);

        jMenuFunctionsViewDataTabular.setText("Προβολή δεδομένων Covid19 ανά χώρα");
        jMenuFunctionsViewDataTabular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFunctionsViewDataTabularActionPerformed(evt);
            }
        });
        jMenuFunctions.add(jMenuFunctionsViewDataTabular);

        jMenuFunctionsViewDataOnMap.setText("Προβολή δεδομένων Covid19 σε χάρτη");
        jMenuFunctionsViewDataOnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFunctionsViewDataOnMapActionPerformed(evt);
            }
        });
        jMenuFunctions.add(jMenuFunctionsViewDataOnMap);
        jMenuFunctions.add(jSeparatorFunctions);

        jMenuFunctionsExit.setText("Έξοδος");
        jMenuFunctionsExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFunctionsExitActionPerformed(evt);
            }
        });
        jMenuFunctions.add(jMenuFunctionsExit);

        jMenuBarBasic.add(jMenuFunctions);

        setJMenuBar(jMenuBarBasic);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFunctionsManageDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFunctionsManageDataActionPerformed
        jDialogManageData.setVisible(true);
    }//GEN-LAST:event_jMenuFunctionsManageDataActionPerformed

    private void jMenuFunctionsExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFunctionsExitActionPerformed
        Object[] options = {"Ναι", "Όχι", "Άκυρο"};
        int choice = JOptionPane.showOptionDialog(null, "Σίγουρα θέλετε να κλείσετε την εφαρμογή;", "Κλείσιμο",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuFunctionsExitActionPerformed

    private void jButtonLoadFromHttpAPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadFromHttpAPIActionPerformed
        // Επιλεγμένο radiobutton actionCommand (deaths, recovered ή confirmed)
        String strDataType = buttonGroupDataType.getSelection().getActionCommand();

        // Κλήση API και κρατάω το jsonString που επιστρέφει ως αποτέλεσμα
        try {
            OkHTTPManager httpCall = new OkHTTPManager(strDataType);
            String jsonString = httpCall.getResponseString();

            // Επεξεργασία του jsonString με βάση του τύπου δεδομένων που ζητήθηκαν
            JsonManager jsonManager = new JsonManager(jsonString, strDataType);
            countriesResults = jsonManager.getCountriesResults();
            //jProgressBar1.setValue(WIDTH);
        } catch (Exception e) {
            jLabelStatus.setText("Σφάλμα σύνδεσης με το Http API");
            JOptionPane.showMessageDialog(null, "Σφάλμα σύνδεσης με το Http API", "Σύνδεση με Http API", JOptionPane.ERROR_MESSAGE);
            return;
        }

        jLabelStatus.setText("Request: " + strDataType + ". Αντλήθηκαν δεδομένα για " + countriesResults.size() + " χώρες.");
        JOptionPane.showMessageDialog(null, "Request: " + strDataType + ". Αντλήθηκαν δεδομένα για " + countriesResults.size() + " χώρες.", "Σύνδεση με Http API", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonLoadFromHttpAPIActionPerformed

    private void jDialogManageDataWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogManageDataWindowClosing

        jLabelStatus.setText("Κατάσταση -");
    }//GEN-LAST:event_jDialogManageDataWindowClosing

    private void jButtonInsertCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertCountriesActionPerformed
        // Τα δεδομένα είναι φορτωμένα μέσω του HTTP query στο countriesResults List
        // Αποθήκευση στη ΒΔ των χωρών που δεν υπάρχουν ήδη
        int added_countries = db.insertCountriesIntoDB(countriesResults);
        if (added_countries >= 0) {
            jLabelStatus.setText("Προστέθηκαν " + added_countries + " νέες χώρες στη ΒΔ");
            JOptionPane.showMessageDialog(null, "Προστέθηκαν " + added_countries + " νέες χώρες στη ΒΔ", "Εισαγωγή χωρών", JOptionPane.INFORMATION_MESSAGE);
            stats = db.dbRecordsInfo();
            jLabelCountriesInDB.setText(String.valueOf(stats[0]));
            jLabelDeathsInDB.setText(String.valueOf(stats[1]));
            jLabelRecoveredInDB.setText(String.valueOf(stats[2]));
            jLabelConfirmedInDB.setText(String.valueOf(stats[3]));
            jLabelTotalRecords.setText(String.valueOf(stats[4]));
        } else {
            jLabelStatus.setText("Δεν υπάρχει σύνδεση με τον DB Server");
            JOptionPane.showMessageDialog(null, "Δεν υπάρχει σύνδεση με τον DB Server", "Εισαγωγή χωρών", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInsertCountriesActionPerformed

    private void jButtonInsertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataActionPerformed
        // Τα δεδομένα είναι φορτωμένα μέσω του HTTP query στο countriesResults List

        int added_data = db.insertCovidDataIntoDB(countriesResults); // Μετρητής εγγραφών που έγιναν insert στη ΒΔ
        this.countriesResults.clear();
        if (added_data >= 0) {
            jLabelStatus.setText("Συνολικά προστέθηκαν " + added_data + " νέες εγγραφές στη ΒΔ");
            JOptionPane.showMessageDialog(null, "Συνολικά προστέθηκαν " + added_data + " νέες εγγραφές στη ΒΔ", "Εισαγωγή δεδομένων", JOptionPane.INFORMATION_MESSAGE);
            stats = db.dbRecordsInfo();
            jLabelCountriesInDB.setText(String.valueOf(stats[0]));
            jLabelDeathsInDB.setText(String.valueOf(stats[1]));
            jLabelRecoveredInDB.setText(String.valueOf(stats[2]));
            jLabelConfirmedInDB.setText(String.valueOf(stats[3]));
            jLabelTotalRecords.setText(String.valueOf(stats[4]));
        } else {
            jLabelStatus.setText("Δεν υπάρχει σύνδεση με τον DB Server");
            JOptionPane.showMessageDialog(null, "Δεν υπάρχει σύνδεση με τον DB Server", "Εισαγωγή δεδομένων", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonInsertDataActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Object[] options = {"Ναι", "Όχι", "Άκυρο"};
        int choice = JOptionPane.showOptionDialog(null, "Σίγουρα θέλετε να κλείσετε την εφαρμογή;", "Κλείσιμο",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButtonDeleteCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCountriesActionPerformed

        Object[] options = {"Ναι", "Όχι", "Άκυρο"};
        int choice = JOptionPane.showOptionDialog(null, "Η διαγραφή των χωρών θα διαγράψει και όλα τα συνδεδεμένα δεδομένα τους. Είστε σίγουροι;", "Διαγραφή χωρών",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (choice == JOptionPane.YES_OPTION) {
            int deleted_data = db.deleteAllTablesDataFromDB();
            this.countriesResults.clear();
            if (deleted_data >= 0) {
                jLabelStatus.setText("Συνολικά διαγράφηκαν " + deleted_data + " εγγραφές από τη ΒΔ");
                JOptionPane.showMessageDialog(null, "Συνολικά διαγράφηκαν " + deleted_data + " εγγραφές από τη ΒΔ", "Διαγραφή δεδομένων", JOptionPane.INFORMATION_MESSAGE);
                stats = db.dbRecordsInfo();
                jLabelCountriesInDB.setText(String.valueOf(stats[0]));
                jLabelDeathsInDB.setText(String.valueOf(stats[1]));
                jLabelRecoveredInDB.setText(String.valueOf(stats[2]));
                jLabelConfirmedInDB.setText(String.valueOf(stats[3]));
                jLabelTotalRecords.setText(String.valueOf(stats[4]));
            } else {
                jLabelStatus.setText("Δεν υπάρχει σύνδεση με τον DB Server");
                JOptionPane.showMessageDialog(null, "Δεν υπάρχει σύνδεση με τον DB Server", "Διαγραφή δεδομένων", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButtonDeleteCountriesActionPerformed

    private void jButtonDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteDataActionPerformed
        String strDataType = buttonGroupDataType.getSelection().getActionCommand();

        Object[] options = {"Ναι", "Όχι", "Άκυρο"};
        int choice = JOptionPane.showOptionDialog(null, "Σίγουρα επιθυμείτε τη διαγραφή των δεδομένων τύπου \"" + strDataType + "\" από όλες τις χώρες;", "Διαγραφή δεδομένων",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (choice == JOptionPane.YES_OPTION) {
            int deleted_data = db.deleteCoviddataFromDB(strDataType);
            this.countriesResults.clear();
            if (deleted_data >= 0) {
                jLabelStatus.setText("Διαγράφηκαν " + deleted_data + " εγγραφές τύπου \"" + strDataType + "\" από τη ΒΔ");
                JOptionPane.showMessageDialog(null, "Διαγράφηκαν " + deleted_data + " εγγραφές τύπου \"" + strDataType + "\" από τη ΒΔ", "Διαγραφή δεδομένων", JOptionPane.INFORMATION_MESSAGE);
                stats = db.dbRecordsInfo();
                jLabelCountriesInDB.setText(String.valueOf(stats[0]));
                jLabelDeathsInDB.setText(String.valueOf(stats[1]));
                jLabelRecoveredInDB.setText(String.valueOf(stats[2]));
                jLabelConfirmedInDB.setText(String.valueOf(stats[3]));
                jLabelTotalRecords.setText(String.valueOf(stats[4]));
            } else {
                jLabelStatus.setText("Δεν υπάρχει σύνδεση με τον DB Server");
                JOptionPane.showMessageDialog(null, "Δεν υπάρχει σύνδεση με τον DB Server", "Διαγραφή δεδομένων", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_jButtonDeleteDataActionPerformed

    private void jMenuFunctionsViewDataTabularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFunctionsViewDataTabularActionPerformed
        // TODO add your handling code here:
        if (stats[0]>0) {
            new JFrameViewDataTabular().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Δεν υπάρχουν καταχωρημένες χώρες στη ΒΔ. Εισάγετε χώρες και δεδομένα από τη 'Διαχείριση δεδομένων Covid19'", "Προβολή δεδομένων χωρών σε πίνακα", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuFunctionsViewDataTabularActionPerformed

    private void jMenuFunctionsViewDataOnMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFunctionsViewDataOnMapActionPerformed
        if (stats[0]>0) {
            new jFrameViewDataOnMap().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Δεν υπάρχουν καταχωρημένες χώρες στη ΒΔ. Εισάγετε χώρες και δεδομένα από τη 'Διαχείριση δεδομένων Covid19'", "Προβολή δεδομένων χωρών σε πίνακα", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuFunctionsViewDataOnMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDataType;
    private javax.swing.JButton jButtonDeleteCountries;
    private javax.swing.JButton jButtonDeleteData;
    private javax.swing.JButton jButtonInsertCountries;
    private javax.swing.JButton jButtonInsertData;
    private javax.swing.JButton jButtonLoadFromHttpAPI;
    private javax.swing.JDialog jDialogManageData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelConfirmedInDB;
    private javax.swing.JLabel jLabelCountriesInDB;
    private javax.swing.JLabel jLabelDeathsInDB;
    private javax.swing.JLabel jLabelRecoveredInDB;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTotalRecords;
    private javax.swing.JMenuBar jMenuBarBasic;
    private javax.swing.JMenu jMenuFunctions;
    private javax.swing.JMenuItem jMenuFunctionsExit;
    private javax.swing.JMenuItem jMenuFunctionsManageData;
    private javax.swing.JMenuItem jMenuFunctionsViewDataOnMap;
    private javax.swing.JMenuItem jMenuFunctionsViewDataTabular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonConfirmed;
    private javax.swing.JRadioButton jRadioButtonDeaths;
    private javax.swing.JRadioButton jRadioButtonRecovered;
    private javax.swing.JPopupMenu.Separator jSeparatorFunctions;
    // End of variables declaration//GEN-END:variables
}
